[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
candy-nft-factory = "BdnJUuLWJy38K2At7zdUuCGu64SVwwMTDg4MSsNT6jxx"


[registry]
# url = "https://api.apr.dev"
url = "https://solana-devnet.g.alchemy.com/v2/cJkK2SdqwYHK-8eElur2mNY1zbuN5do4"
# url = "https://solana-devnet.drpc.org"


[provider]
#  cluster = "Localnet"
# cluster = "devnet"
cluster = "https://solana-devnet.g.alchemy.com/v2/cJkK2SdqwYHK-8eElur2mNY1zbuN5do4"
# cluster = "https://solana-devnet.drpc.org"
wallet = "~/.config/solana/id.json"

[scripts]
recover = "solana program deploy --buffer recover.json --upgrade-authority ~/.config/solana/id.json --program-id target/deploy/candy_nft_factory-keypair.json target/deploy/candy_nft_factory.so "
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
mint = "ts-node scripts/mint.ts"
init = "ts-node scripts/init.ts"
listen = "ts-node scripts/listen.ts"
log = "ts-node scripts/getlog.ts"
sign = "ts-node scripts/sign.ts"


