[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
candy-nft-factory = "HDo1KynYNxqtfjpqsotYMvgx2M2yF1FFxTeaiwp4cGdQ"


[registry]
# url = "https://api.apr.dev"
url = "https://solana-devnet.g.alchemy.com/v2/cJkK2SdqwYHK-8eElur2mNY1zbuN5do4"


[provider]
#  cluster = "Localnet"
# cluster = "devnet"
cluster = "https://solana-devnet.g.alchemy.com/v2/cJkK2SdqwYHK-8eElur2mNY1zbuN5do4"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
mint = "ts-node scripts/mint.ts"
init = "ts-node scripts/init.ts"
